export default {
  layers: [
    {
      id: 'background',
      type: 'background',
      layout: {visibility: 'visible'},
      paint: {'background-color': 'rgb(248,249,250)'},
    },
    {
      id: 'landcover_grass',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'grass']],
      paint: {
        'fill-antialias': false,
        'fill-color': 'rgba(141, 185, 115, 1)',
        'fill-opacity': 0.3,
        'fill-outline-color': 'rgba(141, 185, 115, 1)',
      },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'vietnam',
      'source-layer': 'water',
      layout: {visibility: 'visible'},
      paint: {'fill-color': 'rgba(170, 218, 255, 1)'},
    },
    {
      id: 'waterway_river',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'waterway',
      paint: {'line-color': 'rgba(170, 218, 255, 1)'},
    },
    {
      id: 'waterway_other',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'waterway',
      paint: {'line-color': 'rgba(170, 218, 255, 1)'},
    },
    {
      id: 'park',
      type: 'fill',
      source: 'vietnam',
      'source-layer': 'park',
      paint: {'fill-color': 'rgba(192, 236, 174, 1)'},
    },
    {
      id: 'park_outline',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'park',
      paint: {'line-color': 'rgba(172, 241, 146, 1)'},
    },
    {
      id: 'landuse_residential',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landuse',
      maxzoom: 8,
      filter: ['==', 'class', 'residential'],
      layout: {visibility: 'visible'},
      paint: {
        'fill-color': {
          base: 1,
          stops: [
            [9, 'hsla(0, 3%, 85%, 0.84)'],
            [12, 'hsla(35, 57%, 88%, 0.49)'],
          ],
        },
      },
    },
    {
      id: 'landuse_cemetery',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'cemetery'],
      layout: {visibility: 'visible'},
      paint: {'fill-color': 'hsl(75, 37%, 81%)'},
    },
    {
      id: 'landuse_hospital',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'hospital'],
      layout: {visibility: 'visible'},
      paint: {'fill-color': 'rgba(248, 237, 237, 1)'},
    },
    {
      id: 'landuse_school',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'school'],
      layout: {visibility: 'visible'},
      paint: {'fill-color': 'rgb(236,238,204)'},
    },
    {
      id: 'landcover_wood',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'wood']],
      paint: {
        'fill-antialias': false,
        'fill-color': 'hsla(98, 61%, 72%, 0.7)',
        'fill-opacity': 0.4,
      },
    },
    {
      id: 'building',
      type: 'fill',
      source: 'vietnam',
      'source-layer': 'building',
      minzoom: 16,
      maxzoom: 24,
      layout: {visibility: 'visible'},
      paint: {
        'fill-color': 'hsl(35, 8%, 85%)',
        'fill-outline-color': {
          base: 1,
          stops: [
            [13, 'hsla(35, 6%, 79%, 0.32)'],
            [14, 'hsl(35, 6%, 79%)'],
          ],
        },
      },
    },
    {
      id: 'landcover_sand',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'sand']],
      paint: {'fill-color': 'rgba(247, 239, 195, 1)'},
    },
    {
      id: 'road_tertiary_tunnel_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 12,
      maxzoom: 21,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'tertiary'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [11, 0],
            [11.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [2, 0],
            [4, 0.25],
            [10, 2],
            [12, 4],
            [14, 8],
            [16, 16],
            [18, 29],
            [20, 64],
          ],
        },
      },
    },
    {
      id: 'road_secondary_tunnel_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'secondary'],
        ['!=', 'ramp', '1'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [9, 0],
            [9.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [1, 0],
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_primary_tunnel_casing',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'primary', 'primary_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_motorway_tunnel_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['==', 'class', 'motorway']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_trunk_tunnel_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'trunk', 'trunk_link'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_service_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'service'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [14, 0],
            [14.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [12, 0.5],
            [14, 3],
            [16, 8],
            [18, 14],
            [20, 26],
          ],
        },
      },
    },
    {
      id: 'road_residential_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'residential'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [14, 0],
            [14.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [12, 0.5],
            [14, 3],
            [16, 8],
            [18, 14],
            [20, 26],
          ],
        },
      },
    },
    {
      id: 'road_minor_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'minor'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [13, 0],
            [13.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [13, 3],
            [14, 5],
            [16, 12],
            [18, 22],
            [20, 42],
          ],
        },
      },
    },
    {
      id: 'road_tertiary_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 11,
      maxzoom: 21,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'tertiary'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [11, 0],
            [11.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [2, 0],
            [4, 0.25],
            [10, 3],
            [12, 4],
            [14, 8],
            [16, 16],
            [18, 29],
            [20, 64],
          ],
        },
      },
    },
    {
      id: 'road_secondary_link_casing',
      type: 'line',
      metadata: {'mapbox:group': '1444849345966.4436'},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'secondary_link'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 15],
          ],
        },
      },
    },
    {
      id: 'road_secondary_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'secondary'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(207, 202, 205, 1)',
        'line-opacity': {
          stops: [
            [9, 0],
            [9, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [1, 0],
            [9, 0.5],
            [10, 3],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_primary_casing_link',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'primary_link'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_primary_casing',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'primary'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_motorway_link_casing',
      type: 'line',
      metadata: {'mapbox:group': '1444849345966.4436'},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 12,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway_link'],
      ],
      layout: {'line-cap': 'butt', 'line-join': 'round'},
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_motorway_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_trunk_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'trunk'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_minor_tunnel',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'minor', 'minor_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e3e3e3',
        'line-width': {
          base: 1.55,
          stops: [
            [13, 2],
            [14, 4],
            [16, 10],
            [18, 20],
            [20, 40],
          ],
        },
        'line-opacity': {
          stops: [
            [13, 0],
            [13.5, 1],
          ],
        },
      },
    },
    {
      id: 'road_tertiary_tunnel',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'tertiary', 'tertiary_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e3e3e3',
        'line-width': {
          base: 1.55,
          stops: [
            [1, 2],
            [4, 0.25],
            [10, 1.5],
            [12, 3],
            [14, 6],
            [16, 14],
            [18, 28],
            [20, 60],
          ],
        },
      },
    },
    {
      id: 'road_secondary_tunnel',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'secondary', 'secondary_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e3e3e3',
        'line-width': {
          base: 1.4,
          stops: [
            [6.5, 0],
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_primary_tunnel',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'primary', 'primary_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {'line-cap': 'round', 'line-join': 'round'},
      paint: {
        'line-color': '#e3e3e3',
        'line-offset': 0,
        'line-width': {
          base: 1.4,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_motorway_tunnel',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['in', 'class', 'motorway', 'motorway_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': {
          base: 1,
          stops: [
            [5, '#e3e3e3'],
            [6, '#e3e3e3'],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_trunk_tunnel',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 0,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'trunk', 'trunk_link'],
        ['==', 'brunnel', 'tunnel'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        'line-miter-limit': 2,
      },
      paint: {
        'line-color': '#e3e3e3',
        'line-width': {
          base: 1.4,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
        'line-offset': 0,
        'line-blur': 0,
        'line-opacity': 1,
      },
    },
    {
      id: 'road_service',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'service'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#fff',
        'line-width': {
          base: 1.55,
          stops: [
            [4, 0.25],
            [14, 2],
            [16, 6],
            [18, 12],
            [20, 24],
          ],
        },
        'line-opacity': {
          stops: [
            [14, 0],
            [14.5, 1],
          ],
        },
      },
    },
    {
      id: 'road_residential',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 14,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'residential'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#fff',
        'line-width': {
          base: 1.55,
          stops: [
            [4, 0.25],
            [14, 2],
            [16, 6],
            [18, 12],
            [20, 24],
          ],
        },
        'line-opacity': {
          stops: [
            [14, 0],
            [14.5, 1],
          ],
        },
      },
    },
    {
      id: 'road_minor',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'minor']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#fff',
        'line-width': {
          base: 1.55,
          stops: [
            [13, 2],
            [14, 4],
            [16, 10],
            [18, 20],
            [20, 40],
          ],
        },
        'line-opacity': {
          stops: [
            [13, 0],
            [13.5, 1],
          ],
        },
      },
    },
    {
      id: 'road_tertiary',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'tertiary'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#fff',
        'line-width': {
          base: 1.55,
          stops: [
            [1, 2],
            [4, 0.25],
            [10, 1.5],
            [12, 3],
            [14, 6],
            [16, 14],
            [18, 28],
            [20, 60],
          ],
        },
      },
    },
    {
      id: 'road_secondary',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 9,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'secondary'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#ffffff',
        'line-width': {
          base: 1.4,
          stops: [
            [6.5, 0],
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_primary',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'primary'],
      ],
      layout: {'line-cap': 'round', 'line-join': 'round'},
      paint: {
        'line-color': 'rgba(250, 219, 125, 1)',
        'line-offset': 0,
        'line-width': {
          base: 1.4,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_primary_link',
      type: 'line',
      metadata: {'mapbox:group': '1444849345966.4436'},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        [
          'in',
          'class',
          'primary_link',
          'secondary_link',
          'tertiary_link',
          'trunk_link',
        ],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(250, 219, 125, 1)',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_motorway_link',
      type: 'line',
      metadata: {'mapbox:group': '1444849345966.4436'},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        [
          'in',
          'class',
          'primary_link',
          'secondary_link',
          'tertiary_link',
          'trunk_link',
        ],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': {
          base: 1,
          stops: [
            [5, 'rgba(250, 219, 125, 1)'],
            [6, 'rgba(250, 219, 125, 1)'],
          ],
        },
      },
    },
    {
      id: 'road_motorway',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': {
          base: 1,
          stops: [
            [5, 'rgba(250, 219, 125, 1)'],
            [6, 'rgba(250, 219, 125, 1)'],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_trunk',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 0,
      maxzoom: 24,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'trunk']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        'line-miter-limit': 2,
      },
      paint: {
        'line-color': 'rgba(250, 219, 125, 1)',
        'line-width': {
          base: 1.4,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
        'line-offset': 0,
        'line-blur': 0,
        'line-opacity': 1,
      },
    },
    {
      id: 'road_minor_bridge_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'minor'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [13, 0],
            [13.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [13, 3],
            [14, 5],
            [16, 12],
            [18, 22],
            [20, 42],
          ],
        },
      },
    },
    {
      id: 'road_tertiary_bridge_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 12,
      maxzoom: 21,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'tertiary'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'bevel',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [11, 0],
            [11.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [2, 0],
            [4, 0.25],
            [10, 2],
            [12, 4],
            [14, 8],
            [16, 16],
            [18, 29],
            [20, 64],
          ],
        },
      },
    },
    {
      id: 'road_secondary_bridge_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'secondary'],
        ['!=', 'ramp', '1'],
        ['==', 'brunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#cfcdca',
        'line-opacity': {
          stops: [
            [12, 0],
            [12.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [1, 0],
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_motorway_bridge_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', '1'],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_trunk_bridge_casing',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['==', 'class', 'trunk']],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#e9ac77',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [10, 4],
            [12, 8],
            [14, 12],
            [16, 20],
            [18, 40],
            [20, 100],
          ],
        },
      },
    },
    {
      id: 'road_minor_bridge',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'minor'],
        ['==', 'brunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#fff',
        'line-width': {
          base: 1.55,
          stops: [
            [13, 2],
            [14, 4],
            [16, 10],
            [18, 20],
            [20, 40],
          ],
        },
        'line-opacity': {
          stops: [
            [13, 0],
            [13.5, 1],
          ],
        },
      },
    },
    {
      id: 'road_tertiary_bridge',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'tertiary'],
        ['==', 'brunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#fff',
        'line-width': {
          base: 1.55,
          stops: [
            [1, 2],
            [4, 0.25],
            [10, 1.5],
            [12, 3],
            [14, 6],
            [16, 14],
            [18, 28],
            [20, 60],
          ],
        },
      },
    },
    {
      id: 'road_secondary_bridge',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['in', 'class', 'secondary'],
        ['==', 'brunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#ffffff',
        'line-width': {
          base: 1.4,
          stops: [
            [6.5, 0],
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_motorway_bridge',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: ['all', ['==', 'brunnel', 'bridge'], ['==', 'class', 'motorway']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': {
          base: 1,
          stops: [
            [5, 'rgba(250, 219, 125, 1)'],
            [6, 'rgba(250, 219, 125, 1)'],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0],
            [7, 1],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
      },
    },
    {
      id: 'road_trunk_bridge',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 0,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'trunk'],
        ['==', 'brunnel', 'bridge'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        'line-miter-limit': 2,
      },
      paint: {
        'line-color': 'rgba(250, 219, 125, 1)',
        'line-width': {
          base: 1.4,
          stops: [
            [8, 1.5],
            [10, 3],
            [12, 6],
            [14, 10],
            [16, 18],
            [18, 38],
            [20, 96],
          ],
        },
        'line-offset': 0,
        'line-blur': 0,
        'line-opacity': 1,
      },
    },
    {
      id: 'road_oneway_reverse',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 15,
      filter: [
        'all',
        ['==', 'oneway', -1],
        [
          'in',
          'class',
          'motorway',
          'trunk',
          'primary',
          'secondary',
          'tertiary',
          'minor',
          'service',
        ],
      ],
      layout: {
        'icon-image': 'oneway_reverse',
        'icon-padding': 2,
        'icon-rotate': 0,
        'icon-rotation-alignment': 'map',
        'icon-size': {
          stops: [
            [15, 0.5],
            [19, 1],
          ],
        },
        'symbol-placement': 'line',
        'symbol-spacing': 75,
      },
      paint: {'icon-opacity': 0.5},
    },
    {
      id: 'road_oneway',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'transportation',
      minzoom: 16,
      filter: [
        'all',
        ['==', 'oneway', 1],
        [
          'in',
          'class',
          'motorway',
          'trunk',
          'primary',
          'secondary',
          'tertiary',
          'minor',
          'service',
        ],
      ],
      layout: {
        'icon-image': 'oneway',
        'icon-padding': 2,
        'icon-rotate': 0,
        'icon-rotation-alignment': 'map',
        'icon-size': {
          stops: [
            [16, 1],
            [18, 1.5],
          ],
        },
        'symbol-placement': 'line',
        'symbol-spacing': 120,
        'text-size': 20,
      },
      paint: {'icon-opacity': 0.5},
    },
    {
      id: 'road_label',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation_name',
      minzoom: 13,
      filter: ['all'],
      layout: {
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-field': '{name}',
        'text-font': ['Roboto Regular'],
        'text-offset': [0, 0.15],
        'text-size': {
          base: 1,
          stops: [
            [13, 9],
            [14, 11],
            [15, 11],
            [16, 12],
            [17, 13],
            [18, 14],
            [20, 16],
          ],
        },
      },
      paint: {
        'text-color': '#765',
        'text-halo-blur': 0.5,
        'text-halo-width': 1,
      },
    },
    {
      id: 'road_shield',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'transportation_name',
      minzoom: 7,
      filter: ['all', ['<=', 'ref_length', 6]],
      layout: {
        'icon-image': 'default_{ref_length}',
        'icon-rotation-alignment': 'viewport',
        'symbol-placement': {
          base: 1,
          stops: [
            [10, 'point'],
            [11, 'line'],
          ],
        },
        'symbol-spacing': 500,
        'text-field': '{ref}',
        'text-font': ['Roboto Regular'],
        'text-offset': [0, 0.1],
        'text-rotation-alignment': 'viewport',
        'text-size': 10,
        'icon-size': 0.8,
      },
      paint: {},
    },
    {
      id: 'aeroway_fill',
      type: 'fill',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: ['==', '$type', 'Polygon'],
      paint: {'fill-color': 'rgba(229, 228, 224, 1)', 'fill-opacity': 0.7},
    },
    {
      id: 'aeroway_runway',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'runway']],
      paint: {
        'line-color': '#f0ede9',
        'line-width': {
          base: 1.2,
          stops: [
            [11, 3],
            [20, 16],
          ],
        },
      },
    },
    {
      id: 'aeroway_taxiway',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'taxiway'],
      ],
      paint: {
        'line-color': '#f0ede9',
        'line-width': {
          base: 1.2,
          stops: [
            [11, 0.5],
            [20, 6],
          ],
        },
      },
    },
    {
      id: 'house_number',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'housenumber',
      minzoom: 17,
      filter: ['==', '$type', 'Point'],
      layout: {
        'text-field': '{housenumber}',
        'text-font': ['Noto Sans Regular'],
        'text-size': 10,
      },
      paint: {'text-color': 'rgba(212, 177, 146, 1)'},
    },
    {
      id: 'poi_z18-Shop',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 18,
      filter: ['all', ['==', '$type', 'Point'], ['in', 'class', 'shop']],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z18-convenience',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 18,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'convenience'],
        ['<', 'rank', 300],
        ['>=', 'rank', 200],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_food_drink_z18',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 18,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'food_drink'],
        ['>', 'rank', 800],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(180, 111, 27, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z17-Shop',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 17,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'shop'],
        ['>=', 'rank', 200],
        ['<', 'rank', 500],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z17-convenience',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 17,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'convenience'],
        ['<', 'rank', 200],
        ['>=', 'rank', 100],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_food_drink_z17',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'food_drink'],
        ['!in', 'subclass', 'fast_food'],
        ['>', 'rank', 600],
        ['<=', 'rank', 800],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z17-health-medicine',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 17,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'health'],
        ['in', 'subclass', 'medicine'],
      ],
      layout: {
        'icon-image': 'pharmacy_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z17-health',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 17,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'health'],
        ['!=', 'subclass', 'medicine'],
      ],
      layout: {
        'icon-image': '{subclass}_11',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z16-Shop',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 16,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'shop'],
        ['>=', 'rank', 100],
        ['<', 'rank', 200],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z16-convenience',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 16,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'convenience'],
        ['<', 'rank', 100],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_food_drink_z16',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'food_drink'],
        ['!in', 'subclass', 'fast_food'],
        ['>', 'rank', 400],
        ['<=', 'rank', 600],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z15-Shop',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 15,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['<', 'rank', 100],
        ['in', 'class', 'shop'],
        ['>', 'rank', 250],
        ['<=', 'rank', 400],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_food_drink_z15',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'food_drink'],
        ['!in', 'subclass', 'fast_food'],
        ['>', 'rank', 350],
        ['<=', 'rank', 400],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_leisure',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 15,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'leisure']],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(103, 174, 182, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_z14-Shop',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'class', 'shop'],
        ['<', 'rank', 250],
      ],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_food_drink_z14',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'food_drink'],
        ['!in', 'subclass', 'fast_food'],
        ['<=', 'rank', 350],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_parking',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 15,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'subclass', 'parking']],
      layout: {
        'icon-image': '{subclass}_11',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_fuel',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 15,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'subclass', 'fuel']],
      layout: {
        'icon-image': '{subclass}_11',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_mall',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: ['all', ['==', '$type', 'Point'], ['in', 'sublass', 'mall']],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_tourism',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'tourism'],
        ['==', 'subclass', 'attraction'],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(103, 174, 182, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_entertainment',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'subclass', 'theatre', 'cinema', 'artwork'],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_bus',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'subclass', 'bus', 'bus_stop'],
      ],
      layout: {
        'icon-image': '{subclass}_11',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
        'icon-size': 0.75,
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_public',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 14,
      maxzoom: 24,
      filter: ['all', ['==', '$type', 'Point'], ['in', 'class', 'public']],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_tourism_alt2',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'tourism'],
        ['in', 'subclass', 'historic', 'landmark', 'museum', 'zoo'],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_college',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'college']],
      layout: {
        'icon-image': '{class}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
        'symbol-z-order': 'viewport-y',
      },
      paint: {
        'text-color': 'rgba(103, 174, 182, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_hospital',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'health'],
        ['==', 'subclass', 'hospital'],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(138, 168, 88, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_park',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'natural'],
        ['==', 'subclass', 'park'],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(138, 168, 88, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_station',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['in', 'subclass', 'station', 'halt', 'tram_stop', 'bus_station'],
        ['==', 'class', 'transport'],
      ],
      layout: {
        'icon-image': '{subclass}_11',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(87, 131, 190, 1)',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'poi_monument',
      type: 'symbol',
      source: 'vietnam',
      'source-layer': 'poi',
      minzoom: 12,
      maxzoom: 24,
      filter: [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'class', 'tourism'],
        ['==', 'subclass', 'monument'],
      ],
      layout: {
        'icon-image': '{subclass}_15',
        'text-anchor': 'top',
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-max-width': 9,
        'text-offset': [0, 0.6],
        'text-padding': 2,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#b96464',
        'text-halo-blur': 0.5,
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'boundary_4',
      type: 'line',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'boundary',
      filter: ['all', ['in', 'admin_level', 4]],
      layout: {'line-join': 'round'},
      paint: {
        'line-color': '#9e9cab',
        'line-dasharray': [5, 1],
        'line-width': {
          base: 1,
          stops: [
            [4, 0.4],
            [5, 1],
            [12, 1.8],
          ],
        },
      },
    },
    {
      id: 'boundary_2',
      type: 'line',
      source: 'vietnam',
      'source-layer': 'boundary',
      filter: ['all', ['==', 'admin_level', 2]],
      layout: {'line-cap': 'round', 'line-join': 'round'},
      paint: {
        'line-color': 'hsl(248, 1%, 41%)',
        'line-opacity': {
          base: 1,
          stops: [
            [0, 0.4],
            [4, 1],
          ],
        },
        'line-width': {
          base: 1,
          stops: [
            [3, 1],
            [5, 1.2],
            [12, 3],
          ],
        },
      },
    },
    {
      id: 'place_other',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'place',
      filter: [
        'all',
        ['in', 'class', 'hamlet', 'island', 'islet', 'neighbourhood', 'suburb'],
      ],
      layout: {
        'text-field': '{name}',
        'text-font': ['Roboto Condensed Italic'],
        'text-letter-spacing': 0.1,
        'text-max-width': 9,
        'text-size': {
          base: 1.2,
          stops: [
            [12, 10],
            [15, 14],
          ],
        },
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': '#633',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place_village',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'place',
      filter: ['all', ['==', 'class', 'village']],
      layout: {
        'text-field': '{name}',
        'text-font': ['Roboto Regular'],
        'text-max-width': 8,
        'text-size': {
          base: 1.2,
          stops: [
            [10, 12],
            [15, 22],
          ],
        },
      },
      paint: {
        'text-color': '#333',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place_town',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'place',
      filter: ['all', ['==', 'class', 'town']],
      layout: {
        'icon-image': {
          base: 1,
          stops: [
            [0, 'dot_9'],
            [8, ''],
          ],
        },
        'text-anchor': 'bottom',
        'text-field': '{name}',
        'text-font': ['Roboto Regular'],
        'text-max-width': 8,
        'text-offset': [0, 0],
        'text-size': {
          base: 1.2,
          stops: [
            [7, 12],
            [11, 16],
          ],
        },
      },
      paint: {
        'text-color': '#333',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place_city',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'place',
      minzoom: 5,
      filter: ['all', ['==', 'class', 'city']],
      layout: {
        'icon-image': {
          base: 1,
          stops: [
            [0, 'dot_9'],
            [8, ''],
          ],
        },
        'text-anchor': 'bottom',
        'text-field': '{name}',
        'text-font': ['Roboto Medium'],
        'text-max-width': 8,
        'text-offset': [0, 0],
        'text-size': {
          base: 1.2,
          stops: [
            [7, 14],
            [11, 24],
          ],
        },
        'icon-allow-overlap': true,
        'icon-optional': false,
      },
      paint: {
        'text-color': '#333',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place_state',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'place',
      minzoom: 5,
      filter: ['all', ['==', 'class', 'city']],
      layout: {
        'icon-image': {
          base: 1,
          stops: [
            [0, 'dot_9'],
            [8, ''],
          ],
        },
        'text-anchor': 'bottom',
        'text-field': '{name}',
        'text-font': ['Roboto Medium'],
        'text-max-width': 8,
        'text-offset': [0, 0],
        'text-size': {
          base: 1.2,
          stops: [
            [7, 14],
            [11, 24],
          ],
        },
        'icon-allow-overlap': true,
        'icon-optional': false,
      },
      paint: {
        'text-color': '#333',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place_country',
      type: 'symbol',
      metadata: {},
      source: 'vietnam',
      'source-layer': 'place',
      minzoom: 2,
      filter: ['all', ['==', 'class', 'country']],
      layout: {
        'icon-image': {
          base: 1,
          stops: [
            [0, 'dot_9'],
            [8, ''],
          ],
        },
        'text-anchor': 'bottom',
        'text-field': '{name}',
        'text-font': ['Roboto Medium'],
        'text-offset': [0, 0],
        'text-size': {
          base: 1.2,
          stops: [
            [7, 14],
            [11, 24],
          ],
        },
        'icon-allow-overlap': true,
        'icon-optional': false,
        'symbol-spacing': 250,
        'text-max-width': 10,
      },
      paint: {
        'text-color': '#333',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
  ],
  id: '18abc5vij',
};
